AWSTemplateFormatVersion: 2010-09-09

Description:
  S3 bucket template.

  This is for testing only.

Resources: 
  myS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties: 
      AccessControl: Private
      Tags: 
        - Key: cc
          Value: "4711"

Outputs: 
  BucketName:
    Value: !Ref myS3Bucket
    Description: Name of the bucket